stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker build -t node-app:latest .
  tags:
    - dev

sonarqube-check:
  stage: test
  image: node-app:latest  # Ensure you are using a Node.js image
  script:
    # Set the package version
    - PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo sonar.projectVersion=${PACKAGE_VERSION} >> sonar-project.properties

    # Run the Sonar Scanner
    - npm run sonar-scanner -- -Dsonar.projectKey=node-todo-app -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
    
  #allow_failure: true
  only:
    - master
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker compose up -d
  tags:
    - dev