stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker build -t node-app:latest .
  tags:
    - dev

sonarqube-check:
  stage: test
  image: 
    name: sonarsource/sonar-scanner-cli:latest  # Use the scanner CLI for analysis
    entrypoint: ["/bin/sh", "-c"]  # Use a shell to run commands
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"  # Fetch all branches
    SONAR_HOST_URL: "http://3.90.163.184:9000/"  # Replace with your SonarQube server URL
    SONAR_LOGIN: "sqp_920d3be40fdf6a9541bf45f657f3a45db506ffd2"  # Replace with your SonarQube token
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner -Dsonar.projectKey=node-todo-app -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
  #allow_failure: true
  only:
    - master
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker compose up -d
  tags:
    - dev