stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker build -t node-app:latest .
  tags:
    - dev

sonarqube-check:
  stage: test  # Adding the correct stage
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner -Dsonar.projectKey=your_project_key -Dsonar.sources=.
  #allow_failure: true
  only:
    - master
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker compose up -d
  tags:
    - dev