stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - docker build -t node-app:latest .
  tags:
    - dev

sonarqube-check:
  stage: test
  image: node:latest  # Use a Node.js image to run npm commands
  script:
    # Install dependencies if needed (ensure package.json is present)
    - npm install
    # Set the package version and add it to sonar-project.properties
    - PACKAGE_VERSION=$(node -p "require('./package.json').version")
    - echo "sonar.projectVersion=${PACKAGE_VERSION}" >> sonar-project.properties

    # Run the Sonar Scanner
    - npx sonar-scanner -Dsonar.projectKey=node-todo-app -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
    
  # allow_failure: true  # Uncomment if you want this job to not fail the pipeline
  only:
    - master
  tags:
    - dev

deploy_job:
  stage: deploy
  script:
    - docker compose up -d
  tags:
    - dev
